general:
  device: cpu
paths:
  data: .data
  tensorboard: development
  logs: .logs
  model_checkpoints: .model/checkpoints
  best_model: .model/best
training:
  epochs: 10
  batch_size: 8
  num_workers: 1
  balanced: True
  classification_augmentation:
    flip: True
    offset: 0.1
    scale: 0.2
    rotation: True
    noise: 25.0
  segmentation_augmentation:
    flip: True
    offset: 0.1
    scale: 0.2
    rotation: True
    noise: 25.0
