general:
  device: mps
  dev: True
paths:
  data: .data
  tensorboard: .runs
  logs: .logs
  model_checkpoints: .model/checkpoints
  best_model: .model/best
training:
  epochs: 20
  batch_size: 16
  num_workers: 1
  balanced: True
  classification_augmentation:
    flip: True
    offset: 0.1
    scale: 0.2
    rotation: True
    noise: 25.0
  segmentation_augmentation:
    flip: True
    offset: 0.1
    scale: 0.2
    rotate: True
    noise: 25.0
